import java.util.Scanner;

class Launch
{
	try {
	
			System.out.println("Exception Handling");
			try {
			Scanner sc = new Scanner(System.in);
			System.out.print("Enter first number to divide :: ");
			int num1 = sc.nextInt();
			
			
			System.out.print("Enter sercond number to divide :: ");
			int num2 = sc.nextInt();
			int result = num1/num2;
			System.out.println("The result is :: "+(result));
			System.out.println("Error Occured");
			}
			catch(Exception E) {
				System.out.println(E);
				E.printStackTrace();
			}
			System.out.println("OutSide inner try cathc");
		}
		catch(Exception E) {
			E.printStackTrace();
	}
}
public class NestedTryCatch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
