/*
Custome exception



*/

import java.util.Scanner;

class InvalidCustomException extends Exception
{
	
}

class Atm
{
	int userId=1212;
	int password = 1111;
	int pw;
	int uid;
	
	public void input()
	{
		Scanner sc = new Scanner(System.in);
		
		System.out.print("Kindly entre use id :: ");
		uid = sc.nextInt();
		
		System.out.print("Kindly Eneter your password :: ");
		pw=sc.nextInt();
		
	}
	public void verify() throws InvalidCustomException
	{
		if((userId==uid) && (password==pw)) {
			System.out.println("Take your cash");
		}
		else
		{
			System.out.println("Are you the owner of card or not ? Bz you enter wrong data ...");
			
			InvalidCustomException ice = new InvalidCustomException();
			System.out.println(ice);
			throw ice;
		}
	}
	
}

class Bank
{
	public void initiate()
	{
		Atm a = new Atm();
		try 
		{
			a.input();
			a.verify();	
		} 
		catch (InvalidCustomException e) 
		{
			e.printStackTrace();
			try 
			{
				a.input();
				a.verify();	
			} 
			catch (InvalidCustomException e1) 
			{
				e1.printStackTrace();
				try 
				{
					a.input();
					a.verify();	
				} 
				catch (InvalidCustomException e2) 
				{
					e2.printStackTrace();
				}
			}
		}
	}
}

public class CustomExceptions {
	
	public static void main(String[] args) {
		System.out.println("Custom Exceptions");
		Bank b = new Bank();
		b.initiate();
	}
}
